### ISSUE TITLE
`dev_postgres`: Add boathouse metadata query.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#48] opened 2020-07-23 00:06 UTC
- Add to `schema.sql` a new table that has the following fields called `boathouses`: reach, boathouse, latitude, longitude.

- Use Ben's upcoming changes in #43 to find the list of boathouses and which reaches they're associated with.

- Use Google to find the latitude and longitude of the boathouses.

- Create a new file called `define_boathouses.sql` that hard-codes into the SQL database the proper values.

- Make sure that `define_boathouses.sql` runs whenever the database is initiated.

**Comment by edsun123** [comment] 2020-07-23 01:03
will take a look at this :)

**Comment by edsun123** [comment] 2020-08-12 00:14
Think it was merged. So I think the issue is done :)

**Closed** 2020-08-18 22:28 UTC
Labels: Postgres, data, good first issue
